#!/bin/bash

TEMP_PATH=$HOME/.kodi/temp
ADDONS_PATH=$HOME/.kodi/addons
USERDATA_PATH=$HOME/.kodi/userdata
MAIN_PATH=$HOME/.kodi

###GET Admin###
GUI='/storage/.kodi/userdata/guisettings.xml'
FINDIN=$GUI
FINDWHAT='"skin.htpt.Admin"'
FINDLINE=`find $FINDIN -type f -exec grep $FINDWHAT /dev/null {} \;`
FINDEXACT=`echo $FINDLINE | grep -o '>[^ ]*<' | sed 's/[<>]//g'`
ADMIN='"'$FINDEXACT'"'
echo ADMIN: $Admin '('$FINDEXACT')'

FOLDER_NAME=skin.htpt
FOLDER1_PATH=$ADDONS_PATH/$FOLDER_NAME
FOLDER2_PATH=$TEMP_PATH/Red_LV3
if [ -d $FOLDER1_PATH ]; then
	cp -f -r $FOLDER1_PATH/* $FOLDER2_PATH
	echo COPY FOLDER: $FOLDER_NAME
	rm -r $FOLDER1_PATH
	echo REMOVING FOLDER: $FOLDER_NAME
fi

FOLDER_NAME=script.htpt.debug
FOLDER1_PATH=$ADDONS_PATH/$FOLDER_NAME
FOLDER2_PATH=$TEMP_PATH/Red_LV3
if [ -d $FOLDER1_PATH ]; then
	cp -f -r $FOLDER1_PATH/* $FOLDER2_PATH
	echo COPY FOLDER: $FOLDER_NAME
	rm -r $FOLDER1_PATH
	echo REMOVING FOLDER: $FOLDER_NAME
fi

FOLDER_NAME=script.htpt.fix
FOLDER1_PATH=$ADDONS_PATH/$FOLDER_NAME
FOLDER2_PATH=$TEMP_PATH/Red_LV3
if [ -d $FOLDER1_PATH ]; then
	cp -f -r $FOLDER1_PATH/* $FOLDER2_PATH
	echo COPY FOLDER: $FOLDER_NAME
	rm -r $FOLDER1_PATH
	echo REMOVING FOLDER: $FOLDER_NAME
fi

FOLDER_NAME=service.htpt
FOLDER1_PATH=$ADDONS_PATH/$FOLDER_NAME
FOLDER2_PATH=$TEMP_PATH/Red_LV3
if [ -d $FOLDER1_PATH ]; then
	cp -f -r $FOLDER1_PATH/* $FOLDER2_PATH
	echo COPY FOLDER: $FOLDER_NAME
	rm -r $FOLDER1_PATH
	echo REMOVING FOLDER: $FOLDER_NAME
fi

FOLDER_NAME=script.htpt.homebuttons
FOLDER1_PATH=$ADDONS_PATH/$FOLDER_NAME
FOLDER2_PATH=$TEMP_PATH/Red_LV3
if [ -d $FOLDER1_PATH ]; then
	cp -f -r $FOLDER1_PATH/* $FOLDER2_PATH
	echo COPY FOLDER: $FOLDER_NAME
	rm -r $FOLDER1_PATH
	echo REMOVING FOLDER: $FOLDER_NAME
fi

FOLDER_NAME=script.htpt.refresh
FOLDER1_PATH=$ADDONS_PATH/$FOLDER_NAME
FOLDER2_PATH=$TEMP_PATH/Red_LV3
if [ -d $FOLDER1_PATH ]; then
	cp -f -r $FOLDER1_PATH/* $FOLDER2_PATH
	echo COPY FOLDER: $FOLDER_NAME
	rm -r $FOLDER1_PATH
	echo REMOVING FOLDER: $FOLDER_NAME
fi

FOLDER_NAME=script.htpt.remote
FOLDER1_PATH=$ADDONS_PATH/$FOLDER_NAME
FOLDER2_PATH=$TEMP_PATH/Red_LV3
if [ -d $FOLDER1_PATH ]; then
	cp -f -r $FOLDER1_PATH/* $FOLDER2_PATH
	echo COPY FOLDER: $FOLDER_NAME
	rm -r $FOLDER1_PATH
	echo REMOVING FOLDER: $FOLDER_NAME
fi

FOLDER_NAME=script.htpt.remote
FOLDER1_PATH=$ADDONS_PATH/$FOLDER_NAME
FOLDER2_PATH=$TEMP_PATH/Red_LV3
if [ -d $FOLDER1_PATH ]; then
	cp -f -r $FOLDER1_PATH/* $FOLDER2_PATH
	echo COPY FOLDER: $FOLDER_NAME
	rm -r $FOLDER1_PATH
	echo REMOVING FOLDER: $FOLDER_NAME
fi

sleep 5

if [ -d $ADDONS_PATH/ ]; then
	rm -fr $ADDONS_PATH/
	echo removing $ADDONS_PATH/
	
if [ -d $ADDONS_PATH/ ]; then
	rm -fr $ADDONS_PATH/
	echo removing $ADDONS_PATH/
fi

sleep 5

FOLDER_NAME=Red_LV3
FOLDER1_PATH=$TEMP_PATH/Red_LV3
FOLDER2_PATH=$ADDONS_PATH
if [ -d $FOLDER1_PATH ]; then
	cp -f -r $FOLDER1_PATH/* $FOLDER2_PATH
	echo COPY FOLDER: $FOLDER_NAME
	rm -r $FOLDER1_PATH
	echo REMOVING FOLDER: $FOLDER_NAME
fi
